<Project Sdk="Microsoft.NET.Sdk">  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>UpdateController.Helper</AssemblyName><Version>0.1.1</Version><PublishSingleFile>true</PublishSingleFile><EnableCompressionInSingleFile>true</EnableCompressionInSingleFile><IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract></PropertyGroup>  <ItemGroup>
  <PackageReference Include="AngleSharp" Version="1.8.1" />
</ItemGroup>
</Project>

