[package]
name = "update-controller"
version = "0.1.4-test.1"
license = "MIT"
description = "Deliberate Windows updates"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
open = "5"
tauri-plugin-notification = "=2.3.3"

[profile.release]
strip = true
lto = true
codegen-units = 1
