import { chromium } from '@playwright/test';
import { mkdirSync } from 'node:fs';
mkdirSync('.impeccable/review', { recursive: true });
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1536, height: 1024 }, reducedMotion: 'reduce' });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://127.0.0.1:1420/');
await page.getByText('Manual control active').waitFor();
await page.screenshot({ path: '.impeccable/review/desktop.png' });
await page.getByRole('button', { name: 'Switch to light theme' }).click();
await page.screenshot({ path: '.impeccable/review/light.png' });
await page.setViewportSize({ width: 700, height: 800 });
await page.screenshot({ path: '.impeccable/review/compact.png' });
await page.getByRole('button', { name: 'Read about Windows security update' }).click();
await page.screenshot({ path: '.impeccable/review/compact-detail.png' });
await page.setViewportSize({ width: 1280, height: 850 });
await page.getByRole('button', { name: 'Settings', exact: true }).click();
await page.screenshot({ path: '.impeccable/review/settings.png' });
console.log(JSON.stringify({ errors, horizontalOverflow: await page.evaluate(() => document.documentElement.scrollWidth > innerWidth) }));
await browser.close();
